"""empty message

Revision ID: 5b351b0065ae
Revises: 
Create Date: 2023-09-17 23:10:38.277094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b351b0065ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('villains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('secret_lair', sa.String(), nullable=True),
    sa.Column('childhood_trauma', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heroesvillains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('villain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], name=op.f('fk_heroesvillains_hero_id_heroes')),
    sa.ForeignKeyConstraint(['villain_id'], ['villains.id'], name=op.f('fk_heroesvillains_villain_id_villains')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heroesvillains')
    op.drop_table('villains')
    op.drop_table('heroes')
    # ### end Alembic commands ###
